### ISSUE TITLE
Announcement post link leads to 404 error

### ISSUE THREAD

**Issue by cdrch** [godot-sdk-integrations/.github#1]
In profile/README.md, the link in the sentence "See the announcement of the [Godot Engine Community SDK Integrations](https://godotengine.org/article/godot-engine-community-sdk-integrations) project for details on the purpose and scope of this project." is incorrect and produces a 404 error.

It should link to [https://godotengine.org/article/godot-sdk-integrations/](https://godotengine.org/article/godot-sdk-integrations/) instead.

**Comment by akien-mga** [comment]
Thanks for the report, fixed!

**Comment by cdrch** [comment]
Thanks for the quick fix!
